$(document).ready(function(){
	$("#gmail").fadeTo('fast',.5);
	$("#outlook").fadeTo('fast',.5);
    $("#yahoo").fadeTo('fast',.5);
    $("#youtube").fadeTo('fast',.5);
    $("#netflix").fadeTo('fast',.5);
    $("#drive").fadeTo('fast',.5);
    $("#photos").fadeTo('fast',.5);
    $("#docs").fadeTo('fast',.5);
    $("#keep").fadeTo('fast',.5);
    $("#github").fadeTo('fast',.5);
    $("#wordpress").fadeTo('fast',.5);
    $("#codecademy").fadeTo('fast',.5);
    $("#forums").fadeTo('fast',.5);

	$("#gmail").mouseenter(function(){
		$("#gmail").fadeTo('fast',1);
	});
	$("#outlook").mouseenter(function(){
		$("#outlook").fadeTo('fast',1);
	});
	$("#yahoo").mouseenter(function(){
		$("#yahoo").fadeTo('fast',1);
	});
	$("#youtube").mouseenter(function(){
		$("#youtube").fadeTo('fast',1);
	});
	$("#netflix").mouseenter(function(){
		$("#netflix").fadeTo('fast',1);
	});
	$("#drive").mouseenter(function(){
		$("#drive").fadeTo('fast',1);
	});
	$("#photos").mouseenter(function(){
		$("#photos").fadeTo('fast',1);
	});
	$("#docs").mouseenter(function(){
		$("#docs").fadeTo('fast',1);
	});
	$("#keep").mouseenter(function(){
		$("#keep").fadeTo('fast',1);
	});
	$("#github").mouseenter(function(){
		$("#github").fadeTo('fast',1);
	});
	$("#wordpress").mouseenter(function(){
		$("#wordpress").fadeTo('fast',1);
	});
	$("#codecademy").mouseenter(function(){
		$("#codecademy").fadeTo('fast',1);
	});
	$("#forums").mouseenter(function(){
		$("#forums").fadeTo('fast',1);
	});

	$("#gmail").mouseleave(function(){
		$("#gmail").fadeTo('slow',.5);
	});
	$("#outlook").mouseleave(function(){
		$("#outlook").fadeTo('slow',.5);
	});
	$("#yahoo").mouseleave(function(){
		$("#yahoo").fadeTo('slow',.5);
	});
	$("#youtube").mouseleave(function(){
		$("#youtube").fadeTo('slow',.5);
	});
	$("#netflix").mouseleave(function(){
		$("#netflix").fadeTo('slow',.5);
	});
	$("#drive").mouseleave(function(){
		$("#drive").fadeTo('slow',.5);
	});
	$("#photos").mouseleave(function(){
		$("#photos").fadeTo('slow',.5);
	});
	$("#docs").mouseleave(function(){
		$("#docs").fadeTo('slow',.5);
	});
	$("#keep").mouseleave(function(){
		$("#keep").fadeTo('slow',.5);
	});
	$("#github").mouseleave(function(){
		$("#github").fadeTo('slow',.5);
	});
	$("#wordpress").mouseleave(function(){
		$("#wordpress").fadeTo('slow',.5);
	});
	$("#codecademy").mouseleave(function(){
		$("#codecademy").fadeTo('slow',.5);
	});
	$("#forums").mouseleave(function(){
		$("#forums").fadeTo('slow',.5);
	});

	/*$('#links').mouseleave(function(){
	$("#gmail").stop();
	$("#outlook").stop();
    $("#yahoo").stop();
    $("#youtube").stop();
    $("#netflix").stop();
    $("#drive").stop();
    $("#photos").stop();
    $("#docs").stop();
    $("#keep").stop();
    $("#github").stop();
    $("#wordpress").stop();
    $("#codecademy").stop();
    $("#forums").stop();
    }); */
});